app_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /product    
    
app_document:
    resource: "@AppBundle/Resources/config/routing/document.yml"
    prefix:   /document   
    
app_partner:
    resource: "@AppBundle/Resources/config/routing/partner.yml"
    prefix:   /partner